version: '3'

services:
  postgresdb:
    image: postgres
    hostname: postgres
    ports:
      - "6343:5432"
    networks:
      - app-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thymeleaf_site
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgresdb
    ports:
      - "5556:80"
    networks:
      - app-tier
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
networks:
  app-tier:
    driver: bridge
volumes:
  postgres-data:
